name = "386Architecture"
description = "Zola port of the BOOTSTRA.386."
license = "MIT"
homepage = "https://github.com/ronynn/386Architecture"
min_version = "0.10.1"
demo = "https://ronynn.github.io/386Architecture"

[author]
name = "ronynn"
homepage = "https://github.com/ronynn"
